name: compile

on:
  push:
    paths-ignore:
    - LICENSE
    - README.md
  pull_request:
    paths-ignore:
    - LICENSE
    - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm_version: [ "1.11", "1.12" ]


    steps:
      - uses: actions/checkout@v1

      - name: Set environment variables
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          SCRIPTING_PATH=$GITHUB_WORKSPACE/addons/sourcemod/scripting
          GAMEDATA_PATH=$GITHUB_WORKSPACE/addons/sourcemod/gamedata
          EXT_PATH=$GITHUB_WORKSPACE/addons/sourcemod/extensions
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTING_PATH=$SCRIPTING_PATH" >> $GITHUB_ENV
          echo "INCLUDE_PATH=$SCRIPTING_PATH/include" >> $GITHUB_ENV
          echo "GAMEDATA_PATH=$GAMEDATA_PATH" >> $GITHUB_ENV
          echo "EXT_PATH=$EXT_PATH" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compile gokz plugins
        run: |
          echo -e "\nCompiling plugins..."
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-replays.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-slayonend.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-measure.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-playermodels.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-core.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-global.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-jumpstats.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-mode-simplekz.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-chat.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-mode-vanilla.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-saveloc.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-momsurffix.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-tips.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-quiet.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-racing.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-goto.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-mode-kztimer.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-localranks.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-anticheat.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-pistol.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-hud.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-paint.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-errorboxfixer.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-spec.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-jumpbeam.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-localdb.sp
          spcomp64 -O2 -i $includePath -i $INCLUDE_PATH gokz-profile.sp
          mkdir ../plugins && mv ./*.smx ../plugins
        working-directory: ${{ env.SCRIPTING_PATH }}/

      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        with:
          name: gokz-${{ env.GITHUB_SHA_SHORT }}
          path: ./
